spring:
  cloud:
    stream:
      bindings:
        supplier-out-0:
          contentType: application/*+avro
          destination: sensor-topic
        schemaRegistryClient:
          endpoint: http://localhost:8081
        schema:
          avro:
            schema-location: classpath:avro/sensor.avsc
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: 127.0.0.1:29092
server:
  port: 9010